name: Get cache dependencies
description: To get the dependencies from npm
inputs: 
  caching:
    description: To install dependencies manually or not
    required: false
    default: 'true'
outputs:
  used-cache:
    description: To store the used cache files
    value: ${{ steps.install.outputs.cache}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache= '${{inputs.caching}}'" >> $GITHUB_OUTPUT
      shell: bash